# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIMainQueryDialogue.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainQueryDialogue(object):
    def setupUi(self, mainQueryDialogue):
        mainQueryDialogue.setObjectName("mainQueryDialogue")
        mainQueryDialogue.resize(1035, 699)
        self.mainQueryDialogueLayout = QtWidgets.QVBoxLayout(mainQueryDialogue)
        self.mainQueryDialogueLayout.setObjectName("mainQueryDialogueLayout")
        self.timeLocationFrame = QtWidgets.QGroupBox(mainQueryDialogue)
        self.timeLocationFrame.setObjectName("timeLocationFrame")
        self.timeLoationFrameLayout = QtWidgets.QHBoxLayout(self.timeLocationFrame)
        self.timeLoationFrameLayout.setObjectName("timeLoationFrameLayout")
        self.timeLimitFromLabel = QtWidgets.QLabel(self.timeLocationFrame)
        self.timeLimitFromLabel.setObjectName("timeLimitFromLabel")
        self.timeLoationFrameLayout.addWidget(self.timeLimitFromLabel)
        self.timeLimitFrom = QtWidgets.QDateTimeEdit(self.timeLocationFrame)
        self.timeLimitFrom.setCalendarPopup(True)
        self.timeLimitFrom.setObjectName("timeLimitFrom")
        self.timeLoationFrameLayout.addWidget(self.timeLimitFrom)
        self.timeLimitToLabel = QtWidgets.QLabel(self.timeLocationFrame)
        self.timeLimitToLabel.setObjectName("timeLimitToLabel")
        self.timeLoationFrameLayout.addWidget(self.timeLimitToLabel)
        self.timeLimitTo = QtWidgets.QDateTimeEdit(self.timeLocationFrame)
        self.timeLimitTo.setCalendarPopup(True)
        self.timeLimitTo.setObjectName("timeLimitTo")
        self.timeLoationFrameLayout.addWidget(self.timeLimitTo)
        self.timeLimitRecent24hButton = QtWidgets.QPushButton(self.timeLocationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLimitRecent24hButton.sizePolicy().hasHeightForWidth())
        self.timeLimitRecent24hButton.setSizePolicy(sizePolicy)
        self.timeLimitRecent24hButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.timeLimitRecent24hButton.setObjectName("timeLimitRecent24hButton")
        self.timeLoationFrameLayout.addWidget(self.timeLimitRecent24hButton)
        self.timeLimitRecent12hButton = QtWidgets.QPushButton(self.timeLocationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLimitRecent12hButton.sizePolicy().hasHeightForWidth())
        self.timeLimitRecent12hButton.setSizePolicy(sizePolicy)
        self.timeLimitRecent12hButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.timeLimitRecent12hButton.setObjectName("timeLimitRecent12hButton")
        self.timeLoationFrameLayout.addWidget(self.timeLimitRecent12hButton)
        self.timeLimitRecent3hButton = QtWidgets.QPushButton(self.timeLocationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLimitRecent3hButton.sizePolicy().hasHeightForWidth())
        self.timeLimitRecent3hButton.setSizePolicy(sizePolicy)
        self.timeLimitRecent3hButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.timeLimitRecent3hButton.setObjectName("timeLimitRecent3hButton")
        self.timeLoationFrameLayout.addWidget(self.timeLimitRecent3hButton)
        self.timeLimitRecent1hButton = QtWidgets.QPushButton(self.timeLocationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLimitRecent1hButton.sizePolicy().hasHeightForWidth())
        self.timeLimitRecent1hButton.setSizePolicy(sizePolicy)
        self.timeLimitRecent1hButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.timeLimitRecent1hButton.setObjectName("timeLimitRecent1hButton")
        self.timeLoationFrameLayout.addWidget(self.timeLimitRecent1hButton)
        spacerItem = QtWidgets.QSpacerItem(266, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.timeLoationFrameLayout.addItem(spacerItem)
        self.locationLimitLabel = QtWidgets.QLabel(self.timeLocationFrame)
        self.locationLimitLabel.setObjectName("locationLimitLabel")
        self.timeLoationFrameLayout.addWidget(self.locationLimitLabel)
        self.locationLimit = QtWidgets.QLineEdit(self.timeLocationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locationLimit.sizePolicy().hasHeightForWidth())
        self.locationLimit.setSizePolicy(sizePolicy)
        self.locationLimit.setMinimumSize(QtCore.QSize(200, 0))
        self.locationLimit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.locationLimit.setObjectName("locationLimit")
        self.timeLoationFrameLayout.addWidget(self.locationLimit)
        self.mainQueryDialogueLayout.addWidget(self.timeLocationFrame)
        self.modifiersFrame = QtWidgets.QGroupBox(mainQueryDialogue)
        self.modifiersFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.modifiersFrame.setObjectName("modifiersFrame")
        self.modifiersFrameLayout = QtWidgets.QHBoxLayout(self.modifiersFrame)
        self.modifiersFrameLayout.setObjectName("modifiersFrameLayout")
        self.placeholderForModifiersFrame = QtWidgets.QLabel(self.modifiersFrame)
        self.placeholderForModifiersFrame.setText("")
        self.placeholderForModifiersFrame.setObjectName("placeholderForModifiersFrame")
        self.modifiersFrameLayout.addWidget(self.placeholderForModifiersFrame)
        self.mainQueryDialogueLayout.addWidget(self.modifiersFrame)
        self.filterFrame = QtWidgets.QFrame(mainQueryDialogue)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterFrame.sizePolicy().hasHeightForWidth())
        self.filterFrame.setSizePolicy(sizePolicy)
        self.filterFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.filterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filterFrame.setObjectName("filterFrame")
        self.filterFrameLayout = QtWidgets.QHBoxLayout(self.filterFrame)
        self.filterFrameLayout.setObjectName("filterFrameLayout")
        self.filterLabel = QtWidgets.QLabel(self.filterFrame)
        self.filterLabel.setObjectName("filterLabel")
        self.filterFrameLayout.addWidget(self.filterLabel)
        self.filterLineEdit = QtWidgets.QLineEdit(self.filterFrame)
        self.filterLineEdit.setObjectName("filterLineEdit")
        self.filterFrameLayout.addWidget(self.filterLineEdit)
        self.mainQueryDialogueLayout.addWidget(self.filterFrame)
        self.resultTable = QtWidgets.QTableView(mainQueryDialogue)
        self.resultTable.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.resultTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultTable.setAlternatingRowColors(True)
        self.resultTable.setSortingEnabled(True)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.horizontalHeader().setSortIndicatorShown(True)
        self.mainQueryDialogueLayout.addWidget(self.resultTable)
        self.actionFilter_Selected_Value = QtWidgets.QAction(mainQueryDialogue)
        self.actionFilter_Selected_Value.setObjectName("actionFilter_Selected_Value")
        self.actionMark_Unmark_Selected_Rows = QtWidgets.QAction(mainQueryDialogue)
        self.actionMark_Unmark_Selected_Rows.setObjectName("actionMark_Unmark_Selected_Rows")

        self.retranslateUi(mainQueryDialogue)
        QtCore.QMetaObject.connectSlotsByName(mainQueryDialogue)

    def retranslateUi(self, mainQueryDialogue):
        _translate = QtCore.QCoreApplication.translate
        mainQueryDialogue.setWindowTitle(_translate("mainQueryDialogue", "Form"))
        self.timeLocationFrame.setTitle(_translate("mainQueryDialogue", "Time Location Filter"))
        self.timeLimitFromLabel.setText(_translate("mainQueryDialogue", "From:"))
        self.timeLimitToLabel.setText(_translate("mainQueryDialogue", "To:"))
        self.timeLimitRecent24hButton.setText(_translate("mainQueryDialogue", "24h"))
        self.timeLimitRecent12hButton.setText(_translate("mainQueryDialogue", "12h"))
        self.timeLimitRecent3hButton.setText(_translate("mainQueryDialogue", "3h"))
        self.timeLimitRecent1hButton.setText(_translate("mainQueryDialogue", "1h"))
        self.locationLimitLabel.setText(_translate("mainQueryDialogue", "Location:"))
        self.modifiersFrame.setTitle(_translate("mainQueryDialogue", "Custom Filters"))
        self.filterLabel.setText(_translate("mainQueryDialogue", "Result Filter"))
        self.actionFilter_Selected_Value.setText(_translate("mainQueryDialogue", "Filter with selected Value"))
        self.actionFilter_Selected_Value.setToolTip(_translate("mainQueryDialogue", "Filter result table using the value in the selected cell"))
        self.actionMark_Unmark_Selected_Rows.setText(_translate("mainQueryDialogue", "Mark to Highlight Rows"))
        self.actionMark_Unmark_Selected_Rows.setToolTip(_translate("mainQueryDialogue", "Mark or unmark to highlight selected Rows"))
